// <auto-generated />
using System;
using DotaDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotaDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260127065224_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotaDashboard.Models.Entities.Hero", b =>
                {
                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TotalPicks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer");

                    b.HasKey("HeroId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Heroes_Name");

                    b.HasIndex("TotalPicks")
                        .HasDatabaseName("IX_Heroes_TotalPicks");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("DotaDashboard.Models.Entities.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("MatchesProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Target")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JobId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Jobs_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Jobs_Status");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Jobs_Type");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("DotaDashboard.Models.Entities.Match", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WinnerRadiant")
                        .HasColumnType("boolean");

                    b.HasKey("MatchId");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("IX_Matches_ProcessedAt");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("IX_Matches_StartTime");

                    b.HasIndex("WinnerRadiant")
                        .HasDatabaseName("IX_Matches_WinnerRadiant");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("DotaDashboard.Models.Entities.MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRadiant")
                        .HasColumnType("boolean");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HeroId")
                        .HasDatabaseName("IX_MatchPlayers_HeroId");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("IX_MatchPlayers_MatchId");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_MatchPlayers_PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .HasDatabaseName("IX_MatchPlayers_Match_Player");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("DotaDashboard.Models.Entities.Player", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TotalAssists")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDeaths")
                        .HasColumnType("integer");

                    b.Property<int>("TotalKills")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Players_Name");

                    b.HasIndex("TotalMatches")
                        .HasDatabaseName("IX_Players_TotalMatches");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DotaDashboard.Models.Entities.MatchPlayer", b =>
                {
                    b.HasOne("DotaDashboard.Models.Entities.Hero", "Hero")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotaDashboard.Models.Entities.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotaDashboard.Models.Entities.Player", "Player")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DotaDashboard.Models.Entities.Hero", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("DotaDashboard.Models.Entities.Match", b =>
                {
                    b.Navigation("MatchPlayers");
                });

            modelBuilder.Entity("DotaDashboard.Models.Entities.Player", b =>
                {
                    b.Navigation("MatchPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
